<h1>Settings</h1>
<?php echo validation_errors(); ?>
<?php if (isset($error)) echo '<div class="alert alert-danger">' . $error . '</div>'; ?>
<?php echo form_open_multipart('admin/settings'); ?>
<div class="mb-3">
    <label for="site_title" class="form-label">Site Title</label>
    <input type="text" name="site_title" id="site_title" class="form-control" value="<?php echo $settings['site_title']; ?>">
</div>
<div class="mb-3">
    <label for="meta_description" class="form-label">Meta Description</label>
    <textarea name="meta_description" id="meta_description" class="form-control"><?php echo $settings['meta_description']; ?></textarea>
</div>
<div class="mb-3">
    <label for="meta_keywords" class="form-label">Meta Keywords</label>
    <textarea name="meta_keywords" id="meta_keywords" class="form-control"><?php echo $settings['meta_keywords']; ?></textarea>
</div>
<div class="mb-3">
    <label for="countdown_date" class="form-label">Countdown Date</label>
    <input type="text" name="countdown_date" id="countdown_date" class="form-control" value="<?php echo $settings['countdown_date']; ?>">
</div>
<div class="mb-3">
    <label for="logo" class="form-label">Logo</label>
    <input type="file" name="logo" id="logo" class="form-control">
    <?php if ($settings['logo']): ?>
        <img src="<?php echo base_url('uploads/' . $settings['logo']); ?>" alt="Logo" width="100">
    <?php endif; ?>
</div>
<div class="mb-3">
    <label for="favicon" class="form-label">Favicon</label>
    <input type="file" name="favicon" id="favicon" class="form-control">
    <small class="form-text text-muted">Please upload a zip file containing the favicon files generated by <a href="https://favicon.io/favicon-converter/" target="_blank">favicon.io</a>.</small>
    <?php if ($settings['favicon']): ?>
        <p>Current favicon:</p>
        <img src="<?php echo base_url('uploads/' . $settings['favicon']); ?>/favicon-32x32.png" alt="Favicon" width="32">
    <?php endif; ?>
</div>
<div class="mb-3">
    <label for="account_whatsapp" class="form-label">WhatsApp</label>
    <input type="text" name="account_whatsapp" id="account_whatsapp" class="form-control" value="<?php echo $settings['account_whatsapp']; ?>">
</div>
<div class="mb-3">
    <label for="account_instagram" class="form-label">Instagram</label>
    <input type="text" name="account_instagram" id="account_instagram" class="form-control" value="<?php echo $settings['account_instagram']; ?>">
</div>
<div class="mb-3">
    <label for="account_tiktok" class="form-label">TikTok</label>
    <input type="text" name="account_tiktok" id="account_tiktok" class="form-control" value="<?php echo $settings['account_tiktok']; ?>">
</div>
<div class="mb-3">
    <label for="account_facebook" class="form-label">Facebook</label>
    <input type="text" name="account_facebook" id="account_facebook" class="form-control" value="<?php echo $settings['account_facebook']; ?>">
</div>
<div class="mb-3">
    <label for="account_twitter" class="form-label">Twitter</label>
    <input type="text" name="account_twitter" id="account_twitter" class="form-control" value="<?php echo $settings['account_twitter']; ?>">
</div>
<div class="mb-3">
    <label for="account_linkedin" class="form-label">LinkedIn</label>
    <input type="text" name="account_linkedin" id="account_linkedin" class="form-control" value="<?php echo $settings['account_linkedin']; ?>">
</div>
<div class="mb-3">
    <label for="contact_address" class="form-label">Address</label>
    <input type="text" name="contact_address" id="contact_address" class="form-control" value="<?php echo $settings['contact_address']; ?>">
</div>
<div class="mb-3">
    <label for="contact_phone" class="form-label">Phone</label>
    <input type="text" name="contact_phone" id="contact_phone" class="form-control" value="<?php echo $settings['contact_phone']; ?>">
</div>
<div class="mb-3">
    <label for="contact_email" class="form-label">Email</label>
    <input type="text" name="contact_email" id="contact_email" class="form-control" value="<?php echo $settings['contact_email']; ?>">
</div>
<div class="mb-3">
    <label for="opening_days" class="form-label">Opening Days</label>
    <input type="text" name="opening_days" id="opening_days" class="form-control" value="<?php echo $settings['opening_days']; ?>">
</div>
<div class="mb-3">
    <label for="opening_hours" class="form-label">Opening Hours</label>
    <input type="text" name="opening_hours" id="opening_hours" class="form-control" value="<?php echo $settings['opening_hours']; ?>">
</div>
<div class="mb-3 form-check">
    <input type="checkbox" name="show_about" id="show_about" class="form-check-input" value="1" <?php echo $settings['show_about'] ? 'checked' : ''; ?>>
    <label for="show_about" class="form-check-label">Show About Us Section</label>
</div>
<div class="mb-3 form-check">
    <input type="checkbox" name="show_services" id="show_services" class="form-check-input" value="1" <?php echo $settings['show_services'] ? 'checked' : ''; ?>>
    <label for="show_services" class="form-check-label">Show Services Section</label>
</div>
<div class="mb-3 form-check">
    <input type="checkbox" name="show_gallery" id="show_gallery" class="form-check-input" value="1" <?php echo $settings['show_gallery'] ? 'checked' : ''; ?>>
    <label for="show_gallery" class="form-check-label">Show Gallery Section</label>
</div>
<div class="mb-3 form-check">
    <input type="checkbox" name="show_contact" id="show_contact" class="form-check-input" value="1" <?php echo $settings['show_contact'] ? 'checked' : ''; ?>>
    <label for="show_contact" class="form-check-label">Show Contact Section</label>
</div>
<button type="submit" class="btn btn-primary">Save Settings</button>
<?php echo form_close(); ?>
